# Generated by Django 4.2.5 on 2023-09-06 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_mascota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='descripcion',
            new_name='raza',
        ),
    ]
