# Generated by Django 4.2.5 on 2023-10-05 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mascota',
            new_name='Mascotas',
        ),
    ]
