# Generated by Django 4.2.5 on 2023-09-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_mascota_raza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='avisos',
        ),
        migrations.AddField(
            model_name='contacto',
            name='edad',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
