# Generated by Django 4.2.5 on 2023-09-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_qrcodescan_remove_mascota_imagen_mascota_qr_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRCodeScan',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(null=True, upload_to='mascotas'),
        ),
    ]
