# Generated by Django 4.2.5 on 2023-09-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_delete_qrcodescan_remove_mascota_qr_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('breed', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='pet_photos/')),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='ubicacion_lat',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='ubicacion_lon',
        ),
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.PositiveIntegerField(),
        ),
    ]
