# Generated by Django 4.2.5 on 2023-10-05 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_remove_mascota_raza_mascota_raza_perro_mascota_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='raza_perro',
        ),
        migrations.AddField(
            model_name='mascota',
            name='Raza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='aplicacion.raza'),
        ),
    ]
