# Generated by Django 4.2.5 on 2023-09-07 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_pet_remove_mascota_ubicacion_lat_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
