# Generated by Django 4.2.5 on 2023-09-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_delete_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField(max_length=2, null=True)),
                ('raza', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('telefono', models.CharField(max_length=10)),
                ('imagen', models.ImageField(null=True, upload_to='mascotas')),
            ],
        ),
    ]
