# Generated by Django 4.2.5 on 2023-10-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_alter_mascota_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='genero',
            field=models.CharField(choices=[('Macho', 'Masculino'), ('Hembra', 'Femenino')], max_length=10, null=True),
        ),
    ]
