# Generated by Django 4.2.5 on 2023-10-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_alter_mascota_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='chip',
            field=models.BooleanField(choices=[('Si', 'TRUE'), ('No', 'FALSE')], default=False),
        ),
        migrations.AddField(
            model_name='mascota',
            name='imagen2',
            field=models.ImageField(null=True, upload_to='mascotas'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='imagen3',
            field=models.ImageField(null=True, upload_to='mascotas'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='imagen4',
            field=models.ImageField(null=True, upload_to='mascotas'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='imagen5',
            field=models.ImageField(null=True, upload_to='mascotas'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='miedos',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='personalidad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='tamaño',
            field=models.CharField(choices=[('Grande', 'Grande'), ('Mediano', 'Mediana'), ('Pequeño', 'Pequeña')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='vacunas',
            field=models.BooleanField(choices=[('Si', 'TRUE'), ('No', 'FALSE')], default=False),
        ),
    ]
