# Generated by Django 4.2.5 on 2023-10-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_mascota_chip_mascota_imagen2_mascota_imagen3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='chip',
            field=models.BooleanField(choices=[('SI', 'SI'), ('NO', 'NO')], default=False),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='genero',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tamaño',
            field=models.CharField(choices=[('Grande', 'Grande'), ('Mediano', 'Mediano'), ('Pequeño', 'Pequeño')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='vacunas',
            field=models.BooleanField(choices=[('SI', 'SI'), ('NO', 'NO')], default=False),
        ),
    ]
