# Generated by Django 4.2.5 on 2023-09-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_alter_pet_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='edad',
            field=models.PositiveIntegerField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.PositiveIntegerField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='edad',
            field=models.PositiveIntegerField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='raza',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
