# Generated by Django 4.2.5 on 2023-09-28 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0013_alter_contacto_edad_alter_mascota_edad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pet',
        ),
    ]
