# Generated by Django 4.2.5 on 2023-11-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0015_alimentos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentos',
            name='precio',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
