# Generated by Django 4.2.5 on 2023-11-23 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0017_cliente_carrito'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alimentos',
            new_name='Producto',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
