# Generated by Django 4.2.5 on 2023-11-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0018_rename_alimentos_producto_delete_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(max_length=10),
        ),
    ]
