# Generated by Django 4.2.5 on 2023-12-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0020_direccion_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='ubicacion_escaneo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
